In [1]:
import numpy as np
import quantum_circuit as zq

In [2]:
# x_gate = zq.Gate.x()
# qc = zq.QuantumCircuit(zq.QuantumRegister(1), zq.ClassicalRegister(1))
# qc.apply(x_gate)

In [8]:
i = zq.Gate.i()
x = zq.Gate.x()
z = zq.Gate.z()
zx = z.tensor(x)
 
print(zx.amplitudes)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0. -0. -1.]
 [ 0.  0. -1. -0.]]


In [18]:
gate = zq.Gate.h() @ zq.Gate.z() @ zq.Gate.h()
#print(gate.qubits)
print(f"{gate.amplitudes} \nequals\n {x.amplitudes}")

[[0. 1.]
 [1. 0.]] 
equals
 [[0. 1.]
 [1. 0.]]
